# Generated by Django 5.2.6 on 2025-10-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='is_active',
        ),
    ]
