# Generated by Django 5.2.6 on 2025-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
